-- Creacion de secuencias para las tablas

CREATE SEQUENCE seq_rol START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_usuario START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_usuario_rol START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_sala START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_reserva START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_log_reserva START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_log_cancelacion START WITH 1 INCREMENT BY 1;