CREATE SEQUENCE usuario_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE sala_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE reserva_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE log_reserva_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE log_cancel_seq START WITH 1 INCREMENT BY 1;
